# springboot +mybatisPlus +druid
#项目配置
spring:
  datasource:
    dynamic:
      primary: users
      datasource:
        orders:
          url: jdbc:mysql://192.168.200.23:3306/yhkj-demo1?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: M0Mdeeax4zmY
        users:
          url: jdbc:mysql://192.168.200.23:3306/yhkj-demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: M0Mdeeax4zmY


#mybatis 配置:
mybatis:
  # 加载全局的配置文件
  config-location: classpath:mybatis/mybatis-config.xml
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mapper/*.xml
  # 配置数据库实体包路径
  type-aliases-package: com.txy.**.domain