spring:
  application:
    name: springdataredis

#redis配置 对应RedisProperties 类
  redis:
    host: 192.168.200.42
    port: 6379
    database: 0
    password: yhkjyfzx
    timeout: 10s

    jedis:
      pool:
        max-active: 8 #连接池最大连接数，默认是8 负数表示没有限制
        max-idle: 8 #连接数最小空闲数，默认是8 负数表示没有限制
        min-idle: 0 #连接池最小空闲连接数 默认是0
        max-wait: -1 #连接池最大阻塞等待时间 单位：毫秒 默认是-1 表示不限制