spring:
  application:
    name: mybatis-xml

  datasource:
    url: jdbc:mysql://192.168.200.23:3306/user?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: M0Mdeeax4zmY
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.txy..mybatis.domain
  mapper-locations: classpath:mybatis/mapper/*.xml
