#项目配置
txy:
  version: 1.0.0

#环境配置
server:
  #服务器的HTTP端口号 默认8080
  port: 8081
  servlet:
    #应用访问路径
    context-path: /study-mybqtisPlus

spring:
  application:
    name: springboot-mybatisPlus

  #数据库配置
  datasource:
    druid:
      url: jdbc:mysql://192.168.200.23:3306/quality?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: xysstgs
      password: xystyfzx
      driver-class-name: com.mysql.cj.jdbc.Driver




  #mybatisPlus 配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.txy.domain