# springboot +mybatisPlus +druid
#项目配置
txy:
  version: 1.0.0

#环境配置
server:
  #服务器的HTTP端口号 默认8080
  port: 8081
  servlet:
    #应用访问路径
    context-path: /study-mybqtisPlus

spring:
  application:
    name: springboot-mybatisPlus

  #数据库配置
  datasource:
    druid:
      master:
        url: jdbc:mysql://192.168.200.23:3306/quality?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: xysstgs
        password: xystyfzx
        driver-class-name: com.mysql.cj.jdbc.Driver
      slave:
        url: jdbc:mysql://192.168.200.23:3306/srdg-base?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: xysstgs
        password: xystyfzx
        driver-class-name: com.mysql.cj.jdbc.Driver

      #监控
      stat-view-servlet:
        enabled: true
        #访问地址规则
        url-pattern: /druid/*
        #是否允许清空统计数据
        reset-enable: true
        #监控页面的登录账户
        login-username: admin
        #监控页面的登录密码
        login-password: admin






  #mybatisPlus 配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.txy.domain
  # 指定日志输出
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
